### ISSUE TITLE
how to config the API Key in MacOS

### ISSUE THREAD

**Issue by set-path** [kazgu/zotero-chatgpt#1]
I have installed the plugin, but I don't know how to config the API Key and how to use it.

**Comment by kazgu** [comment]
you can config the API key from Zotero Settings .
<img width="822" alt="Screenshot 2023-04-18 at 22 13 22" src="https://user-images.githubusercontent.com/7955157/232806356-a33624ec-2cfb-49ad-bb83-e9555b4a0f26.png">

In the readerTab choose ChatGPT and input the qustions or paste  .
<img width="1439" alt="Screenshot 2023-04-18 at 22 14 52" src="https://user-images.githubusercontent.com/7955157/232806464-6a03b320-a437-473e-9217-a7b6792520ef.png">
